security:
  basic:
    enabled: false
  user:
      name: user
      password: password
  enable-csrf: false
spring:
  application:
    name: api-gateway
server:
  port: ${SERVER_PORT:0}

eureka:
  client:
    service-url:
      defult-zone:http://172.16.8.36:16801/eureka/
